base_url = "https://mdberkey.github.io"

title = "mdberkey"

compile_sass = true

build_search_index = false

theme = "terminimal"

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
menu_items = [
    {name = "about me", url = "$BASE_URL"},
    {name = "resume", url = "$BASE_URL/resume"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "archive", url = "$BASE_URL/archive"},
]

logo_text = "mdberkey"

author = "Michael Berkey"

page_titles = "combined"
