base_url = "https://mdberkey.github.io"

title = "mdberkey"

compile_sass = true

build_search_index = false

theme = "terminimal"

generate_feeds = true

feed_filenames = ["rss.xml"]

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
menu_items = [
    {name = "about me", url = "$BASE_URL"},
    {name = "resume", url = "$BASE_URL/resume"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "rss", url = "https://mdberkey.github.io/rss.xml"}
]

logo_text = "（'-'）.｡oO(mdberkey)"

author = "Michael Berkey"

page_titles = "combined"

favicon = "/favicon.png"
favicon_mimetype = "image/png"

social_links = [
    { name = "email", url = "mailto:mberkey2@gmail.com"},
    { name = "github", url = "https://github.com/mdberkey"},
    { name = "linkedin", url = "https://www.linkedin.com/in/michael-berkey1/"},
]

post_view_navigation_prompt = ""
